import UIKit

/// Renders a single tracked purchase — its details, deadlines, and receipt
/// photo — into a one-page PDF suitable for attaching to a return or
/// warranty claim email. Runs entirely on-device with UIGraphicsPDFRenderer;
/// nothing here touches the network or leaves local storage.
enum ClaimPackGenerator {
  static func makePDF(for item: TrackedItem, receiptImage: UIImage?) -> Data {
    let pageWidth: CGFloat = 612 // US Letter, 72pt per inch
    let pageHeight: CGFloat = 792
    let margin: CGFloat = 48
    let contentWidth = pageWidth - margin * 2

    let renderer = UIGraphicsPDFRenderer(bounds: CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight))

    return renderer.pdfData { context in
      context.beginPage()
      var y = margin

      let titleAttributes: [NSAttributedString.Key: Any] = [
        .font: UIFont.boldSystemFont(ofSize: 22)
      ]
      (item.name as NSString).draw(at: CGPoint(x: margin, y: y), withAttributes: titleAttributes)
      y += 32

      let subtitleAttributes: [NSAttributedString.Key: Any] = [
        .font: UIFont.systemFont(ofSize: 14),
        .foregroundColor: UIColor.darkGray
      ]
      ("Claim pack — generated by Owned" as NSString).draw(at: CGPoint(x: margin, y: y), withAttributes: subtitleAttributes)
      y += 28

      y = drawDivider(in: context.cgContext, y: y, margin: margin, width: contentWidth)

      let labelAttributes: [NSAttributedString.Key: Any] = [
        .font: UIFont.boldSystemFont(ofSize: 13)
      ]
      let valueAttributes: [NSAttributedString.Key: Any] = [
        .font: UIFont.systemFont(ofSize: 13)
      ]

      func drawRow(_ label: String, _ value: String) {
        (label as NSString).draw(at: CGPoint(x: margin, y: y), withAttributes: labelAttributes)
        (value as NSString).draw(at: CGPoint(x: margin + 140, y: y), withAttributes: valueAttributes)
        y += 22
      }

      drawRow("Retailer", item.retailer.isEmpty ? "—" : item.retailer)
      drawRow("Purchase date", item.purchaseDate.formatted(date: .long, time: .omitted))
      if let price = item.priceDisplay {
        drawRow("Price paid", price)
      }
      if let category = item.category {
        drawRow("Category", category.label)
      }

      y += 12
      y = drawDivider(in: context.cgContext, y: y, margin: margin, width: contentWidth)

      let sectionAttributes: [NSAttributedString.Key: Any] = [
        .font: UIFont.boldSystemFont(ofSize: 16)
      ]
      ("Deadlines" as NSString).draw(at: CGPoint(x: margin, y: y), withAttributes: sectionAttributes)
      y += 24

      if item.deadlines.isEmpty {
        ("No return window or warranty tracked." as NSString).draw(at: CGPoint(x: margin, y: y), withAttributes: valueAttributes)
        y += 22
      } else {
        for deadline in item.deadlines.sorted(by: { $0.date < $1.date }) {
          let statusLabel: String
          switch deadline.status() {
          case .active: statusLabel = "Active"
          case .expiringSoon: statusLabel = "Expiring soon"
          case .expired: statusLabel = "Expired"
          }
          drawRow(deadline.kind.label, "\(deadline.date.formatted(date: .long, time: .omitted)) — \(statusLabel)")
        }
      }

      if !item.notes.isEmpty {
        y += 12
        y = drawDivider(in: context.cgContext, y: y, margin: margin, width: contentWidth)
        ("Notes" as NSString).draw(at: CGPoint(x: margin, y: y), withAttributes: sectionAttributes)
        y += 24
        let notesRect = CGRect(x: margin, y: y, width: contentWidth, height: 100)
        (item.notes as NSString).draw(in: notesRect, withAttributes: valueAttributes)
        y += 100
      }

      if let receiptImage {
        y += 12
        y = drawDivider(in: context.cgContext, y: y, margin: margin, width: contentWidth)
        ("Receipt" as NSString).draw(at: CGPoint(x: margin, y: y), withAttributes: sectionAttributes)
        y += 24

        let maxImageHeight = max(0, pageHeight - y - margin)
        let aspect = receiptImage.size.width / max(receiptImage.size.height, 1)
        var drawWidth = contentWidth
        var drawHeight = drawWidth / aspect
        if drawHeight > maxImageHeight {
          drawHeight = maxImageHeight
          drawWidth = drawHeight * aspect
        }
        receiptImage.draw(in: CGRect(x: margin, y: y, width: drawWidth, height: drawHeight))
      }
    }
  }

  /// Drafts the actual claim/return request message — the part that takes
  /// the most mental effort once the paperwork itself is ready. The PDF
  /// above bundles the receipt and deadline details into something to
  /// attach; this drafts the words to send alongside it, pre-filled with
  /// everything Owned already knows and a clearly-marked blank for the one
  /// thing only the person filing the claim can supply: what's actually
  /// wrong with the item, or why it's being returned.
  static func makeClaimMessage(for item: TrackedItem, deadline: TrackedDeadline?) -> String {
    let itemName = item.name.isEmpty ? "this item" : item.name
    let retailer = item.retailer.isEmpty ? "your store" : item.retailer
    let purchaseDate = item.purchaseDate.formatted(date: .long, time: .omitted)
    let priceLine = item.priceDisplay.map { " for \($0)" } ?? ""

    if deadline?.kind == .warranty {
      let expiryLine = deadline.map { " The warranty runs through \($0.date.formatted(date: .long, time: .omitted))." } ?? ""
      return """
      Subject: Warranty claim — \(itemName)

      Hello,

      I'm writing to file a warranty claim for \(itemName), purchased from \(retailer) on \(purchaseDate)\(priceLine).\(expiryLine)

      [Describe what's wrong with the item here.]

      I've attached a claim pack with the purchase details and receipt. Please let me know what you need from me to move forward, and what the next steps are.

      Thank you,
      """
    }

    let closesLine = deadline.map { " The return window closes \($0.date.formatted(date: .long, time: .omitted))." } ?? ""
    return """
    Subject: Return request — \(itemName)

    Hello,

    I'd like to return \(itemName), purchased from \(retailer) on \(purchaseDate)\(priceLine).\(closesLine)

    [Add your reason for the return here, if needed.]

    I've attached a claim pack with the purchase details and receipt. Could you let me know the return process and refund timeline?

    Thank you,
    """
  }

  private static func drawDivider(in context: CGContext, y: CGFloat, margin: CGFloat, width: CGFloat) -> CGFloat {
    context.setStrokeColor(UIColor.lightGray.cgColor)
    context.setLineWidth(0.5)
    context.move(to: CGPoint(x: margin, y: y))
    context.addLine(to: CGPoint(x: margin + width, y: y))
    context.strokePath()
    return y + 16
  }
}
